apps/cart/urls.py
from django.conf.urls import url
from apps.cart import views

urlpatterns = [
    url(r'^add$', views.CartAddView.as_view(), name='cart_add'),
    url(r'^$', views.CartInfoView.as_view(), name='cart_info'),
    url(r'^update$', views.CartUpdateView.as_view(), name='cart_update'),
    url(r'^delete$', views.CartDeleteView.as_view(), name='cart_delete'),
]

apps/goods/urls.py
from django.conf.urls import url
from apps.goods import views

urlpatterns = [
    url(r'^index$', views.IndexView.as_view(), name='index'),
    url(r'^detail(?P<sku_id>\d+)$', views.DetailView.as_view(), name='detail'),
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', views.ListView.as_view(), name='list'),
]

apps/order/urls.py
from django.conf.urls import url
from apps.order import views

urlpatterns = [
    url(r'^$', views.OrderInfoView.as_view(), name='show'),
    url(r'^commit$', views.OrderCommitView.as_view(), name='commit'),
    url(r'^pay$', views.OrderPayView.as_view(), name='pay'),
    url(r'^check$', views.PayCheckView.as_view(), name='check'),
    url(r'^comment/(?P<order_id>\d+)$', views.OrderCommentView.as_view(), name='comment'),
]

apps/user/urls.py
from django.conf.urls import url
from apps.user import views


urlpatterns = [
    url(r'^register$', views.RegisterView.as_view(), name='register'),
    url(r'^active/(?P<token>.*)', views.ActiveView.as_view(), name='active'),
    url(r'^login$', views.LoginView.as_view(), name='login'),
    url(r'^logout$', views.LogoutView.as_view(), name='logout'),
    url(r'^$', views.UserInfoView.as_view(), name='user_center_info'),
    url(r'^user_center_order/(?P<page>\d+)$', views.UserOrderView.as_view(), name='user_center_order'),
    url(r'^user_center_site$', views.UserSiteView.as_view(), name='user_center_site'),
]

dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
    url(r'^search', include('haystack.urls')), # 全文检索框架
    url(r'^user/', include('apps.user.urls', namespace='user')),
    url(r'^cart/', include('apps.cart.urls', namespace='cart')),
    url(r'^order/', include('apps.order.urls', namespace='order')),
    url(r'^', include('apps.goods.urls', namespace='goods'))
]

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from apps.goods.models import GoodsSKU
from django_redis import get_redis_connection
from util.mixin import LoginRequiredMixin


# Create your views here.
# /cart/add  sku_id count
class CartAddView(View):
    '''购物车添加视图类'''
    def post(self, request):
        # 校验用户登录
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res': 0, 'errmsg': '用户未登录'})

        # 获取数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 校验数据
        # 校验数据完整性
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验商品数目是否合法
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目有误'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理: 添加购物车
        # 根据redis数据库中是否存在当前商品选择是否累计
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            count += int(cart_count)

        # 校验是否超过库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        conn.hset(cart_key, sku_id, count)

        # 查询购物车数目
        total_count = conn.hlen(cart_key)

        # 返回响应
        return JsonResponse({'res': 5, 'total_count':total_count, 'msg': '添加购物车成功'})


# /cart
class CartInfoView(LoginRequiredMixin, View):
    '''购物车页面'''
    def get(self, request):
        # 获取用户的商品记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % request.user.id
        cart_dict = conn.hgetall(cart_key)

        # 添加商品到skus, 计算总价和总数量
        skus = list()
        total_count = 0
        total_price = 0
        for sku_id, count in cart_dict.items():
            sku = GoodsSKU.objects.get(id=sku_id)
            amount = sku.price*int(count)
            sku.amount = amount
            sku.count = count

            skus.append(sku)
            total_price += amount
            total_count += int(count)

        # 组织上下文
        context = {
            'total_count': total_count,
            'total_price': total_price,
            'skus': skus
        }

        return render(request, 'cart.html', context)


# /cart/update
class CartUpdateView(View):
    '''更新购物车视图类'''
    def post(self, request):
        # 登录校验
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res': 0, 'errmsg': '用户未登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 校验数据
        # 数据完整性
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 数目合法
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '无效的商品数目'})

        # 商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理: 更新购物车
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 验证是否超过库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        conn.hset(cart_key, sku_id, count)

        # 查询购物车总数目
        total = 0
        for val in conn.hvals(cart_key):
            total += int(val)

        # 返回响应
        return JsonResponse({'res': 5, 'total': total, 'msg': '购物车更新成功!'})

# /cart/delete  sku_id
class CartDeleteView(View):
    '''删除购物车视图'''
    def post(self, request):
        # 登录校验
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res': 0, 'errmsg': '用户未登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')

        # 校验数据
        # 数据完整性
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '无效的商品id'})

        # 商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        # 业务处理: 删除购物车商品
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        conn.hdel(cart_key, sku_id)

        # 查询购物车总数目
        total = 0
        for val in conn.hvals(cart_key):
            total += int(val)

        # 返回响应
        return JsonResponse({'res': 3, 'total': total, 'msg': '删除购物车商品成功!'})

templates/base.html
{# 首页, 详情页, 列表页, 登录, 注册 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load staticfiles %}
{% load filters %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 顶部引入文件 #}
    {% block topfiels %}{% endblock topfiels %}
</head>
<body>
    {# 顶部欢迎界面 #}
    {% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:cart_info' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:user_center_order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
    {% endblock header_con %}

    {# 顶部搜索框 #}
    {% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart_info' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count|get_cart_count:user }}</div>
		</div>
	</div>
    {% endblock search_bar %}

    {% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

    {# 底部html #}
    {% block bottom %}{% endblock bottom %}

    {# 底部引入文件 #}
	{% block bottom_files %}{% endblock bottom_files %}

</body>
</html>

templates/base_list_detail.html
{% extends 'base.html' %}
{% load filters %}
{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types|get_obj:'types' %}
                        <li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/base_user_center.html
{% extends 'base_no_cart.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_center_info' %}" {% if page == 'info' %}class="active"{% endif %} >· 个人信息</a></li>
				<li><a href="{% url 'user:user_center_order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:user_center_site' %}" {% if page == 'site' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {% block right_content %}{% endblock right_content %}
    </div>
{% endblock body %}

templates/cart.html
{% extends 'base_no_cart.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-购物车{% endblock title %}
{% block page_title %}购物车{% endblock page_title %}
{% block body %}

	<div class="total_count">全部商品<em>{{ total_count }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>

    <form action="{% url 'order:show' %}" method="post">
        {% csrf_token %}
        {% for sku in skus %}
            <ul class="cart_list_td clearfix">
                <li class="col01"><input type="checkbox" name="sku_ids" value="{{ sku.id }}" checked></li>
                <li class="col02"><img src="{{ sku.image.url }}"></li>
                <li class="col03">{{ sku.name }}<br><em>{{ sku.price }}元/{{ sku.unite }}</em></li>
                <li class="col04">{{ sku.unite }}</li>
                <li class="col05">{{ sku.price }}元</li>
                <li class="col06">
                    <div class="num_add">
                        <a href="javascript:;" class="add fl">+</a>
                        <input type="text" sku_id="{{ sku.id }}" class="num_show fl" value="{{ sku.count }}">
                        <a href="javascript:;" class="minus fl">-</a>
                    </div>
                </li>
                <li class="col07">{{ sku.amount }}元</li>
                <li class="col08"><a href="javascript:;">删除</a></li>
            </ul>
        {% empty %}
            <ul class="cart_list_td clearfix">
                <li style="width: 100%; text-align: center; font-size: 18px;">当前购物车为空&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'goods:index' %}">去逛逛</a></li>
            </ul>
        {% endfor %}

        <ul class="settlements">
            <li class="col01"><input type="checkbox" name="" checked=""></li>
            <li class="col02">全选</li>
            <li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_price }}</em><br>共计<b>{{ total_count }}</b>件商品</li>
            <li class="col04"><input type="submit" value="去结算"></li>
        </ul>
    </form>

{% endblock body %}
{% block bottom_files %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        //设总计为两位小数
        var $totalPrice = $('.settlements .col03 em').text();
        $('.settlements .col03 em').text(parseFloat($totalPrice).toFixed(2));

        // 设置全选
        // 全选框状态变化
        $('.settlements').find(':checkbox').change(function () {
            var isCheck = $('.settlements').find(':checkbox').prop('checked');

            $('.cart_list_td').find(':checkbox').prop('checked', isCheck);

            // 更新总计
            fnUpdateSum();
        });
        // 其他选框状态变化
        $('.cart_list_td').find(':checkbox').change(function () {
            // 统计选中的框与多选框总数
            var checkedNum = $('.cart_list_td').find(':checked').length;
            var allCheckboxNum = $('.cart_list_td').find(':checkbox').length;

            var isCheck = true;
            if(checkedNum < allCheckboxNum)
            {
                isCheck = false;
            }

            $('.settlements').find(':checkbox').prop('checked', isCheck);

            fnUpdateSum();

        });

        // 更新购物车商品数目
        // 添加
        $('.add').click(function(){
            //获取数据,组织参数
            var sku_id = $(this).next().attr('sku_id');
            var count = parseInt($(this).parents('ul').find('.num_show').val()) + 1;

            result = fnUpdateCartInfo(sku_id, count);

            //更新成功后的页面变化
            if(!result.err_update)
            {
                //商品数目
                $(this).next().val(count);

                //商品小结
                fnUpdateAmount($(this).parents('ul'));

                //页面总计(是否选中)
                var isChecked = $(this).parents('ul').find(':checkbox').prop('checked');
                if(isChecked)
                {
                    fnUpdateSum();
                }

                //购物车商品总数目
                $('.total_count em').text(result.total);
            }
        });

        // 减少
        $('.minus').click(function () {
            //获取数据,组织参数
            var sku_id = $(this).prev().attr('sku_id');
            var count = parseInt($(this).parents('ul').find('.num_show').val()) - 1;

            if(count <= 0)
            {
                return;
            }

            result = fnUpdateCartInfo(sku_id, count);

            //更新成功后的页面变化
            if(!result.err_update)
            {
                //商品数目
                $(this).prev().val(count);

                //商品小结
                fnUpdateAmount($(this).parents('ul'));

                //页面总计(是否选中)
                var isChecked = $(this).parents('ul').find(':checkbox').prop('checked');
                if(isChecked)
                {
                    fnUpdateSum();
                }

                //购物车商品总数目
                $('.total_count em').text(result.total);
            }
        });

        // 手动输入
        var preCount = 0;
        $('.num_show').focus(function () {
            preCount = $(this).val();
        });

        $('.num_show').blur(function () {
            //获取数据,组织参数
            var sku_id = $(this).attr('sku_id');
            var count = $(this).parents('ul').find('.num_show').val();

            if(isNaN(count) || count.trim().length == 0 || parseInt(count)<=0)
            {
                $(this).val(preCount);
                return;
            }

            result = fnUpdateCartInfo(sku_id, count);

            //更新成功后的页面变化
            if(!result.err_update)
            {
                //商品数目
                $(this).val(count);

                //商品小结
                fnUpdateAmount($(this).parents('ul'));

                //页面总计(是否选中)
                var isChecked = $(this).parents('ul').find(':checkbox').prop('checked');
                if(isChecked)
                {
                    fnUpdateSum();
                }

                //购物车商品总数目
                $('.total_count em').text(result.total);
            }
            else
            {
                $(this).val(preCount);
            }
        });


        //删除购物车商品
        $('.cart_list_td .col08 a').click(function () {
            var sku_id = $(this).parents('ul').find('.num_show').attr('sku_id');
            var csrf = $('input[name=csrfmiddlewaretoken]').val();

            var params = {
                'sku_id': sku_id,
                'csrfmiddlewaretoken': csrf
            };

            var sku_ul = $(this).parents('ul');

            $.post('/cart/delete', params, function (data) {
                if(data.res == 3)
                {
                    //删除成功
                    //删除商品ul
                    sku_ul.remove();

                    //判断是否为空
                    var allSKUNum = $('.cart_list_td').length;
                    if(allSKUNum == 0)
                    {
                        var $newLi = $('<ul class="cart_list_td clearfix">\n' +
                            '            <li style="width: 100%; text-align: center; font-size: 18px;">当前购物车为空&nbsp;&nbsp;&nbsp;&nbsp;<a href="/index">去逛逛</a></li>\n' +
                            '        </ul>');
                        $('.cart_list_th').after($newLi);
                    }

                    //判断是否选中: 商品总计更新
                    var isChecked = sku_ul.find(':checkbox').prop('checked');
                    if(isChecked)
                    {
                        fnUpdateSum();
                    }

                    //购物车商品总数目更新
                    $('.total_count em').text(data.total);
                }
                else
                {
                    //删除失败
                    alert(data.errmsg);
                }
            });

        });





        // 更新页面总计函数
        function fnUpdateSum()
        {
            // 获取,遍历所有被选中的checkbox并添加
            var total_price = 0;
            var total_count = 0;
            $('.cart_list_td').find(':checked').parents('ul').each(function(){
                total_count += parseInt($(this).find('.num_show').val());
                total_price += parseFloat($(this).children('.col07').text());
            });

            $('.settlements .col03 em').text(total_price.toFixed(2));
            $('.settlements .col03 b').text(total_count);
        }

        //商品小结
        function fnUpdateAmount(sku_ul)
        {
            var price = parseFloat(sku_ul.children('.col05').text());
            var count = parseInt(sku_ul.find('.num_show').val());

            var amount = (price*count).toFixed(2);
            sku_ul.children('.col07').text(amount+'元');
        }

        //更新购物车信息: 发送ajax post请求
        function fnUpdateCartInfo(sku_id, count)
        {
            var csrf = $('input[name=csrfmiddlewaretoken]').val();

            var params = {
                'sku_id': sku_id,
                'count': count,
                'csrfmiddlewaretoken': csrf
            }

            // ajax: post
            // 设置为同步ajax
            $.ajaxSettings.async = false;
            var err_update = false;
            var total = 0;
            $.post('/cart/update', params, function (data) {
                if(data.res == 5)
                {
                    //更新成功
                    err_update = false;
                    total = data.total;
                }
                else
                {
                    //更新失败
                    err_update = true;
                    alert(data.errmsg);
                }
            });
            $.ajaxSettings.async = true;

            return {'total':total, 'err_update': err_update};
        }


    </script>
{% endblock bottom_files %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block topfiels %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiels %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
                <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goods_banners %}
                    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for promotion_banner in promotion_banners %}
                <a href="{{ promotion_banner.url }}"><img src="{{ promotion_banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for title in type.title_banners %}
                    <a href="{% url 'goods:detail' title.sku.id %}">{{ title.sku.name }}</a>
                {% endfor %}
			</div>
			<a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.display_banners %}
                    <li>
                        <h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
                        <a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
                        <div class="prize">¥ {{ banner.sku.price }}</div>
                    </li>
                {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}


{% endblock body %}

templates/list.html
{% extends 'base_list_detail.html' %}
{% block title %}天天生鲜-商品列表{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="{% url 'goods:index' %}">全部分类</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                            <div class="prize">￥{{ sku.name }}</div>
                        </li>
                    {% empty %}
                        暂时没有新品推荐
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}?sort=default" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in sku_page %}
                    <li>
                           <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                           <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                           <div class="operate">
                           <span class="prize">￥{{ sku.name }}</span>
                           <span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
                           <a href="#" class="add_goods" title="加入购物车"></a>
                           </div>
                       </li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if sku_page.has_previous %}
                    <a href="{% url 'goods:list' type.id sku_page.previous_page_number %}?sort={{ sort }}">&lt;上一页</a>
                {% else %}
                    <span>上一页</span>
                {% endif %}

                {% for pindex in pages %}
                    {% if pindex == sku_page.number %}
                        <a href="{% url 'goods:list' type.id pindex %}" class="active">{{ pindex }}</a>
                    {% else %}
                        <a href="{% url 'goods:list' type.id pindex %}" >{{ pindex }}</a>
                    {% endif %}
                {% endfor %}

                {% if sku_page.has_next %}
                    <a href="{% url 'goods:list' type.id sku_page.next_page_number %}?sort={{ sort }}">下一页&gt;</a>
                {% else %}
                    <span>下一页</span>
                {% endif %}
			</div>
		</div>
	</div>

{% endblock main_content %}